### ISSUE TITLE
Activate / Deactivate Video Capture Devices

### ISSUE THREAD

**Issue by beamer311** [bitfocus/companion-module-obs-studio#325]
### Is this a feature relevant to companion itself, and not a specific module?

- [x] I believe this to be a feature for companion, and is not specific to a module

### Is there an existing issue for this?

- [x] I have searched for similiar existing issues

### Describe the feature

Are you able to add a new Companion button for enabling/disabling video inputs? I’m capturing both the program and multiview outputs from a video switcher, and I need the ability to toggle inputs on or off depending on the active scene in OBS.

### Usecases

Allows you to integrate multiple video inputs into the program and preview views within OBS. I worked with an engineer to create and implement switching functions for an RGBlink Mini Edge, and having the ability to enable/disable inputs will help optimize the workflow.

**Comment by beamer311** [comment]
Hi Julusian, 

Noticed this was moved to closes but I don’t see a response. Do you know if the issue of being unable to disable video input sources in obs has been resolved?

**Comment by h07d0q** [comment]
Hey!
I was watching this issue since I'm looking for a possibility to activate/deactivate a "Video Capture Device" - not changing the visibility with “Set Source Visibility” that does not solve my issue.
<img width="716" height="608" alt="Image" src="https://github.com/user-attachments/assets/2c14cfb4-f5c8-4489-92ab-bdba51eb402a" />

I found a tool which explains the need for this, because I have the same issue, but not with a USB device:
https://github.com/turecross321/ObsAutoRefresh
Setting "SetInputSettings" without changing a parameter seems to restart the source (activating/deactivating it).
Today "SetInputSettings" is used by the action "Set Source Text" but this will not work for my VideoCapture Device...

Can you consider to reopen this issue?

**Comment by bryce-seifert** [comment]
@h07d0q Thanks for the clearer explanation, research and the screenshot, I appreciate it. I have retitled the issue and reopened it, and will try to get to it too
